In [1]:
import matplotlib.pyplot as plt
import numpy as np
import tensorflow as tf
from keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D,MaxPool2D,Flatten,Dense
from tensorflow.keras.preprocessing import image
from tensorflow import keras
import os
import cv2 as cv
import random

In [2]:
#Load Haar Cascade
cascade = cv.CascadeClassifier("haarcascade_frontalface_default.xml")

In [3]:
model = tf.keras.models.load_model('trial.h5')

Loading Model

In [6]:
# detect video feed 
video = cv.VideoCapture(0)
while True:
    ret, frame = video.read()
    
    # grayscale
    gray = cv.cvtColor(frame, cv.COLOR_BGR2GRAY)
    print(gray.shape)
    
    x = 100
    y = 150
    face_recognition = cascade.detectMultiScale(gray,1.1,7)
    
    for (x,y,width,height) in face_recognition:
        face_gray = gray[y:y+height,x:x+width]
        face_color = frame[y:y+height,x:x+width]
        
        cv.rectangle(frame,(x,y),(x+width,y+height),(0,255,0),thickness=2)
        
        face = cascade.detectMultiScale(face_gray)
        
        # if face is detected
        
        if len(face) == 0:
            print("Face is not Detected")
            
            
        # finding the emotion
        
        vid = cv.resize(face_color,[128,128])
        vid = np.expand_dims(vid, axis=0)
            
        vid = vid / 255.0
            
            
        pred = model.predict(vid)      
        print(pred[0])
            
        #making a prediction
        emotion_index =  np.argmax(pred)
        emotion_labels = ["Angry", "Fear", "Happy", "Neutral", "Sad", "Surprised"]
        emotion = emotion_labels[emotion_index]
        
        #video
        cv.putText(frame,emotion,(x, y - 10),cv.FONT_HERSHEY_COMPLEX,1,(0,255,0),thickness=2)
        cv.rectangle(frame,(x,y),(x+width,y+height),(0,255,0),thickness=2)
        print(emotion)
            
    cv.imshow("Video Frame",frame)
    
    if cv.waitKey(1)==ord('q'):
        break   
    
video.release()
cv.destroyAllWindows()
            
            

(480, 640)
1/1 [==============================] - 0s 57ms/step
[0.09370273 0.02865207 0.0033614  0.79485804 0.0764481  0.00297775]
Neutral
(480, 640)
1/1 [==============================] - 0s 59ms/step
[0.0308449  0.01781478 0.00300407 0.9126838  0.03351245 0.00214001]
Neutral
(480, 640)
1/1 [==============================] - 0s 50ms/step
[0.1271882  0.03532927 0.00290734 0.7036876  0.12794028 0.00294727]
Neutral
(480, 640)
1/1 [==============================] - 0s 47ms/step
[0.03932611 0.03148508 0.00347725 0.85460424 0.06788514 0.00322218]
Neutral
(480, 640)
1/1 [==============================] - 0s 48ms/step
[0.00758731 0.01089394 0.00517215 0.95911604 0.01441301 0.00281758]
Neutral
(480, 640)
1/1 [==============================] - 0s 61ms/step
[0.04128658 0.02644151 0.00344363 0.8690983  0.05713833 0.0025916 ]
Neutral
(480, 640)
1/1 [==============================] - 0s 64ms/step
[0.02314541 0.01522782 0.00350055 0.9305173  0.02527783 0.00233108]
Neutral
(480, 640)
1/1 [===========